version: '3'

networks:
  default:
    driver: bridge

services:
  otp:
    container_name: openmove-otp
    ports: ["8080:8080"]
    image: openmove/opentripplanner:1.4.2
    environment:
      - BUILD_GRAPH=False
      - DOWNLOAD_DATA=False
      - JAVA_MX=4G
      - BRANCH=v1.4.0
      - BRANCH_ALIAS=1.4.0
    volumes:
      - ./data/:/data/
    #restart: always

  otp-build:
    container_name: openmove-otp-build
    ports: ["8090:8080"]
    image: openmove/opentripplanner:1.4.2
    environment:
      - BUILD_GRAPH=True
      #TODO - DOWNLOAD_DATA=True
      - JAVA_MX=10G
      - BRANCH=v1.4.0
      - BRANCH_ALIAS=1.4.0
    volumes:
      - ./data/:/data/
    #restart: no
